# Generated by Django 4.2.7 on 2023-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, choices=[('literature', 'Литература'), ('drawing', 'Рисование'), ('cpp', 'C++'), ('orthodoxy', 'Православие'), ('ml', 'ML'), ('py', 'Python')], to='custom_user.interest'),
        ),
    ]
