# Generated by Django 4.2.7 on 2024-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_interest_remove_customuser_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, choices=[('1', 'Литература'), ('2', 'Рисование'), ('3', 'C++'), ('4', 'Православие'), ('5', 'ML'), ('6', 'Python')], to='custom_user.interest'),
        ),
    ]
