# Generated by Django 4.2.7 on 2024-01-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_customuser_interests_alter_interest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(choices=[('lt', 'Литература'), ('dr', 'Рисование'), ('cpp', 'C++'), ('ort', 'Православие'), ('ml', 'ML'), ('py', 'Python')], max_length=30, unique=True),
        ),
    ]
